export const RESTAURANTS = [
  {
    id: 1,
    name: "The Pizza House",
    cuisines: "Pizza, Italian",
    rating: 4.5,
    reviews: "1.2K+",
    priceForTwo: "₹ 200 for two",
    deliveryTime: "30–40 mins",
    freeDelivery: true,
    isVeg: false,
    image:
      "https://images.unsplash.com/photo-1513104890138-7c749659a591?w=600&auto=format&fit=crop&q=80",
  },
  {
    id: 2,
    name: "Burger Point",
    cuisines: "Burgers, Fast Food",
    rating: 4.2,
    reviews: "980+",
    priceForTwo: "₹ 250 for two",
    deliveryTime: "25–35 mins",
    freeDelivery: true,
    isVeg: false,
    image:
      "https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=600&auto=format&fit=crop&q=80",
  },
  {
    id: 3,
    name: "Biryani Blues",
    cuisines: "Biryani, North Indian",
    rating: 4.6,
    reviews: "2.1K+",
    priceForTwo: "₹ 300 for two",
    deliveryTime: "20–30 mins",
    freeDelivery: true,
    isVeg: false,
    image:
      "https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8?w=600&auto=format&fit=crop&q=80",
  },
  {
    id: 4,
    name: "Chinese Wok",
    cuisines: "Chinese, Asian",
    rating: 4.3,
    reviews: "860+",
    priceForTwo: "₹ 220 for two",
    deliveryTime: "30–45 mins",
    freeDelivery: true,
    isVeg: false,
    image:
      "https://images.unsplash.com/photo-1585032226651-759b368d7246?w=600&auto=format&fit=crop&q=80",
  },
  {
    id: 5,
    name: "Green Bowl Salad Co.",
    cuisines: "Salads, Healthy, Continental",
    rating: 4.7,
    reviews: "1.5K+",
    priceForTwo: "₹ 350 for two",
    deliveryTime: "15–25 mins",
    freeDelivery: true,
    isVeg: true,
    image:
      "https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=600&auto=format&fit=crop&q=80",
  },
  {
    id: 6,
    name: "Udupi Grand Pure Veg",
    cuisines: "South Indian, Dosa, Filter Coffee",
    rating: 4.6,
    reviews: "3.4K+",
    priceForTwo: "₹ 180 for two",
    deliveryTime: "20–30 mins",
    freeDelivery: true,
    isVeg: true,
    image:
      "https://images.unsplash.com/photo-1610192244261-3f33de3f55e4?w=600&auto=format&fit=crop&q=80",
  },
  {
    id: 7,
    name: "Taco Bell Fiesta",
    cuisines: "Mexican, Tacos, Burritos",
    rating: 4.1,
    reviews: "750+",
    priceForTwo: "₹ 280 for two",
    deliveryTime: "25–35 mins",
    freeDelivery: false,
    isVeg: false,
    image:
      "https://images.unsplash.com/photo-1565299585323-38d6b0865b47?w=600&auto=format&fit=crop&q=80",
  },
  {
    id: 8,
    name: "Sweet Tooth Bakery",
    cuisines: "Desserts, Cakes, Bakery",
    rating: 4.8,
    reviews: "1.9K+",
    priceForTwo: "₹ 220 for two",
    deliveryTime: "15–20 mins",
    freeDelivery: true,
    isVeg: true,
    image:
      "https://images.unsplash.com/photo-1578985545062-69928b1d9587?w=600&auto=format&fit=crop&q=80",
  },
  {
    id: 9,
    name: "Royal Punjab Dhaba",
    cuisines: "North Indian, Mughlai, Tandoor",
    rating: 4.4,
    reviews: "2.8K+",
    priceForTwo: "₹ 320 for two",
    deliveryTime: "35–45 mins",
    freeDelivery: false,
    isVeg: false,
    image:
      "https://images.unsplash.com/photo-1546833999-b9f581a1996d?w=600&auto=format&fit=crop&q=80",
  },
  {
    id: 10,
    name: "Tokyo Sushi Express",
    cuisines: "Japanese, Sushi, Asian",
    rating: 4.7,
    reviews: "620+",
    priceForTwo: "₹ 450 for two",
    deliveryTime: "25–40 mins",
    freeDelivery: true,
    isVeg: false,
    image:
      "https://images.unsplash.com/photo-1579871494447-9811cf80d66c?w=600&auto=format&fit=crop&q=80",
  },
  {
    id: 11,
    name: "Falafel King",
    cuisines: "Middle Eastern, Lebanese, Wraps",
    rating: 4.3,
    reviews: "890+",
    priceForTwo: "₹ 240 for two",
    deliveryTime: "20–30 mins",
    freeDelivery: true,
    isVeg: true,
    image:
      "https://images.unsplash.com/photo-1593560708920-61dd98c46a4e?w=600&auto=format&fit=crop&q=80",
  },
  {
    id: 12,
    name: "Belgian Waffle House",
    cuisines: "Waffles, Desserts, Shakes",
    rating: 4.5,
    reviews: "1.7K+",
    priceForTwo: "₹ 210 for two",
    deliveryTime: "15–25 mins",
    freeDelivery: true,
    isVeg: true,
    image:
      "https://images.unsplash.com/photo-1562376552-0d160a2f238d?w=600&auto=format&fit=crop&q=80",
  },
];

const CATEGORIES = [
  { id: "all", name: "All", icon: "⊞", bg: "#fff0e6" },
  { id: "pizza", name: "Pizza", icon: "🍕", bg: "#fff5f0" },
  { id: "burger", name: "Burger", icon: "🍔", bg: "#fffbe8" },
  { id: "biryani", name: "Biryani", icon: "🍛", bg: "#fff7ed" },
  { id: "chinese", name: "Chinese", icon: "🍜", bg: "#f5f0ff" },
  { id: "south-indian", name: "South Indian", icon: "🥞", bg: "#eefdf8" },
  { id: "desserts", name: "Desserts", icon: "🍰", bg: "#fff0f3" },
  { id: "beverages", name: "Beverages", icon: "🥤", bg: "#fff7ed" },
  { id: "more", name: "More", icon: "•••", bg: "#f3f4f6" },
];




module.exports = { RESTAURANTS, CATEGORIES };